server:
  servlet:
    context-path: /coupon-server
  port: 8081


#nacos discovery
spring:
  application:
    name: coupon-server

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: coupon-service
        heart-beat-timeout: 20000
        # nacos客户端向服务端发送心跳的时间间隔，时间单位其实是ms
        heart-beat-interval: 5000

    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8858


genwoshuo: ""

management:
  endpoint:
    serviceregistry:
      enabled: true

